
```{r}
library(here)

source(here("00_requirements.R"))
```

```{r}
demographics = read_csv(
  here("Datasets", "demographics.csv"), 
  skip = 2,
  na = "N/A",
  
  col_types = cols(
    Footnotes = col_skip() 
  )
)

print(demographics)
```

```{r}
commuter_data_raw <- read_tsv(here("Datasets", "state_commuter_mode.csv")) %>%
  
  rename(Share = "Commute mode share (percent)")

commuter_data_wide <- commuter_data_raw %>%
  
  filter(Year == 2023) %>%
  
  select(-Year) %>%

  pivot_wider(
    names_from = Mode,
    values_from = Share
  )

print(commuter_data_wide)
```

```{r}
gun_ownership_data <- read_csv(here("Datasets", "gun-ownership-by-state-2025.csv"))

print(gun_ownership_data)
```


```{r}
covid_deaths_raw <- read_csv(here("Datasets", "covid_deaths.csv"))

state_names <- unique(demographics$Location)

latest_state_totals <- covid_deaths_raw %>%
  
  filter(Jurisdiction_Residence %in% state_names) %>%
  mutate(end_date = mdy(data_period_end)) %>%
  group_by(Jurisdiction_Residence) %>%
  arrange(desc(end_date)) %>%
  slice(1) %>%
  ungroup()

print(latest_state_totals)
```


```{r}
merged_data_raw <- read.csv(here("Datasets", "Unemployment_Income_Voting_Merged.csv"))
merged_data_clean <- merged_data_raw[-c(51, 53), -2]

print(merged_data_clean)
```

```{r}
joined_data <- demographics %>%
  left_join(commuter_data_wide, by = c("Location" = "State")) %>%
  left_join(gun_ownership_data, by = c("Location" = "state")) %>% 
  left_join(latest_state_totals, by = c("Location" = "Jurisdiction_Residence")) %>%
  left_join(merged_data_clean, by = c("Location" = "State.Name"))

print(head(joined_data))
glimpse(joined_data)
```